### ISSUE TITLE
number of frames per utterance for MELD visual features

### ISSUE THREAD

**Issue by dondongwon** [declare-lab/MM-Align#2]
Hi thanks for your work.

I've been checking out the feature shape and it seems that for dialogue 1 utterance 1 there are only 6 frames (which means that it is 6/25 of a second), which doesn't make sense. 

![image](https://user-images.githubusercontent.com/43928520/231928767-f8aa31e9-6f8a-4f6a-9ef5-898ebc66b503.png)

Is the frame rate of 25 fps accurate?

**Comment by Clement25** [comment]
It seems what you are checking is the tokenization ids so that 6 tokens do not mean the duration is 6/25 sec. The frame rate is only applied to audio.

**Comment by dondongwon** [comment]
The last line in the image is the shape of the  the video_features, the resnet101 features that was used, which seems to be (6,2048). Resnet extracts features by per image frame, which means that only 6 frames were extracted for the 1th dialogue and 1th utterance. 

More clarification would be appreciated. Thanks!

**Comment by Clement25** [comment]
I see. These are pre-align features, which are obtained by average-pooling the 25fps audio/video features to the same length of text ids. This preprocessing just aims to reduce the computational cost, since OT is very slow and original audio/video sequences are too long.

**Comment by dondongwon** [comment]
I see, thanks for the information!
