### ISSUE TITLE
word tokenizer for MELD 

### ISSUE THREAD

**Issue by dondongwon** [declare-lab/MM-Align#3]
Hi thanks for your work.

I've been trying to decode the 'token_ids' to actual words. 

Did you use Bert_tokenizer to tokenize the words? It seems unlikely because when I try to decode the tokens it gives me strange outputs .
![image](https://user-images.githubusercontent.com/43928520/231929012-233848e3-bfee-44fa-bca3-f55861cbef34.png)

How do we decode the tokens to the original words?

**Comment by Clement25** [comment]
Just glove mapping here.
